name: Build and Test Server API

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches-ignore: [ "main" ]

defaults:
    run:
        working-directory: server

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    strategy:
        # TODO: Testing multiple versions requires figuring out 
        # a way to mongoose.disconnect() without affecting all jobs using the same connection. 
        # Maybe use Docker instances?
        matrix:
            node-version: [19.x]
            
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Build and Test
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        npm ci
        npm run ts-build --if-present
        npm test